name: eds_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
# ui
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  extended_image: ^8.1.0
  flutter:
    sdk: flutter
# net
  http: ^1.1.0
#state manager
  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.2.0
  flutter_riverpod: ^2.4.3
  

dev_dependencies:
# state manager
  build_runner: ^2.4.6
  freezed: ^2.4.5
  riverpod_generator: ^2.3.3

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
    - assets/images/